# Generated by Django 4.2.3 on 2023-08-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('price_started', models.IntegerField(default=0)),
                ('location', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='events/')),
                ('is_like', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
