# Generated by Django 4.2.3 on 2023-08-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
